// GENERATED by scripts/generate_d1_schema_manifest.mjs from migrations-d1/*.sql. Do not edit.
// Regenerate with: node scripts/generate_d1_schema_manifest.mjs
export type D1ColumnKind = "text" | "int" | "real" | "bool" | "json";
export interface D1TableSchema { file: string; primaryKey: string[]; columns: Record<string, D1ColumnKind> }
export const D1_SCHEMA: Record<string, D1TableSchema> = {
  "agencies": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "name": "text",
      "slug": "text",
      "legal_name": "text",
      "website_url": "text",
      "logo_url": "text",
      "primary_color": "text",
      "owner_user_id": "text",
      "status": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "agency_members": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "user_id": "text",
      "role": "text",
      "status": "text",
      "invited_by_user_id": "text",
      "invited_at": "text",
      "joined_at": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "profiles": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "email": "text",
      "full_name": "text",
      "avatar_url": "text",
      "timezone": "text",
      "status": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "clients": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "name": "text",
      "slug": "text",
      "industry": "text",
      "website_url": "text",
      "logo_url": "text",
      "primary_contact_name": "text",
      "primary_contact_email": "text",
      "status": "text",
      "internal_notes": "text",
      "created_by_user_id": "text",
      "updated_by_user_id": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "contacts": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "email"
    ],
    "columns": {
      "email": "text",
      "name": "text",
      "company": "text",
      "title": "text",
      "personal_website": "text",
      "social_links": "json",
      "topics_of_interest": "json",
      "networking_goals": "text",
      "hidden_from_directory": "bool",
      "events_attended": "json",
      "first_seen_at": "text",
      "last_seen_at": "text",
      "updated_at": "text",
      "archived_at": "text"
    }
  },
  "events": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "name": "text",
      "slug": "text",
      "event_type": "text",
      "status": "text",
      "start_at": "text",
      "end_at": "text",
      "timezone": "text",
      "description": "text",
      "internal_goal": "text",
      "client_facing_goal": "text",
      "primary_producer_user_id": "text",
      "project_manager_user_id": "text",
      "registration_enabled": "bool",
      "venue_enabled": "bool",
      "replay_enabled": "bool",
      "reporting_enabled": "bool",
      "created_by_user_id": "text",
      "updated_by_user_id": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "audit_logs": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "actor_user_id": "text",
      "actor_role": "text",
      "action": "text",
      "resource_type": "text",
      "resource_id": "text",
      "previous_value_json": "json",
      "new_value_json": "json",
      "visibility": "text",
      "ip_address": "text",
      "user_agent": "text",
      "created_at": "text"
    }
  },
  "role_assignments": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "user_id": "text",
      "role": "text",
      "scope_type": "text",
      "scope_id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "assigned_by_user_id": "text",
      "status": "text",
      "starts_at": "text",
      "ends_at": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "client_contacts": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "user_id": "text",
      "name": "text",
      "email": "text",
      "phone": "text",
      "title": "text",
      "role": "text",
      "is_primary": "bool",
      "status": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "contractor_assignments": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "contractor_id": "text",
      "user_id": "text",
      "role": "text",
      "status": "text",
      "call_time_at": "text",
      "end_time_at": "text",
      "assigned_by_user_id": "text",
      "assignment_notes": "text",
      "shared_notes": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "vendor_assignments": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "vendor_id": "text",
      "service_category": "text",
      "status": "text",
      "assigned_by_user_id": "text",
      "due_at": "text",
      "internal_notes": "text",
      "shared_notes": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "speaker_profiles": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "user_id": "text",
      "name": "text",
      "title": "text",
      "company": "text",
      "email": "text",
      "bio": "text",
      "readiness_status": "text",
      "tech_check_status": "text",
      "internal_notes": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "sponsors": {
    "file": "migrations-d1/0001_core.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "name": "text",
      "website_url": "text",
      "tier": "text",
      "status": "text",
      "primary_contact_name": "text",
      "primary_contact_email": "text",
      "internal_notes": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text",
      "booth_headline": "text",
      "booth_description": "text",
      "cta_label": "text",
      "cta_url": "text",
      "lead_routing_email": "text",
      "booth_status": "text",
      "ready_room_status": "text"
    }
  },
  "approval_requests": {
    "file": "migrations-d1/0002_approvals_inbox.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "approval_type": "text",
      "title": "text",
      "description": "text",
      "status": "text",
      "resource_type": "text",
      "resource_id": "text",
      "requested_by_user_id": "text",
      "assigned_to_user_id": "text",
      "assigned_role": "text",
      "due_at": "text",
      "client_visible": "bool",
      "locked": "bool",
      "approved_at": "text",
      "approved_by_user_id": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "approval_comments": {
    "file": "migrations-d1/0002_approvals_inbox.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "approval_request_id": "text",
      "author_user_id": "text",
      "body": "text",
      "visibility": "text",
      "created_at": "text",
      "updated_at": "text",
      "deleted_at": "text"
    }
  },
  "production_inbox_items": {
    "file": "migrations-d1/0002_approvals_inbox.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "event_code": "text",
      "source_channel": "text",
      "status": "text",
      "sender_name": "text",
      "sender_email": "text",
      "subject": "text",
      "summary": "text",
      "possible_match_type": "text",
      "possible_match_id": "text",
      "linked_resource_type": "text",
      "linked_resource_id": "text",
      "next_action": "text",
      "received_at": "text",
      "converted_at": "text",
      "archived_at": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "last_minute_change_requests": {
    "file": "migrations-d1/0002_approvals_inbox.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_id": "text",
      "client_id": "text",
      "event_id": "text",
      "speaker_id": "text",
      "sponsor_id": "text",
      "run_of_show_segment_id": "text",
      "change_type": "text",
      "urgency": "text",
      "risk": "text",
      "status": "text",
      "title": "text",
      "old_version_label": "text",
      "new_version_label": "text",
      "diff_summary": "text",
      "affects_timing": "bool",
      "affects_sponsor_mention": "bool",
      "affects_client_approved_copy": "bool",
      "minutes_until_segment": "int",
      "recommended_action": "text",
      "submitted_by_user_id": "text",
      "decided_by_user_id": "text",
      "submitted_at": "text",
      "decided_at": "text",
      "pushed_to_live_at": "text",
      "rolled_back_at": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "runtime_events": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "slug": "text",
      "name": "text",
      "format": "text",
      "event_type": "text",
      "status": "text",
      "status_before_archive": "text",
      "client_id": "text",
      "client_name": "text",
      "client_slug": "text",
      "description": "text",
      "start_at": "text",
      "end_at": "text",
      "timezone": "text",
      "join_code": "text",
      "crew_code": "text",
      "speaker_code": "text",
      "sponsor_code": "text",
      "vip_code": "text",
      "client_code": "text",
      "registration_enabled": "bool",
      "branding": "json",
      "sessions": "json",
      "source": "text",
      "created_by": "text",
      "created_by_label": "text",
      "created_at": "text",
      "updated_at": "text",
      "archived_at": "text",
      "registration_questions": "json",
      "attendee_session_days": "int"
    }
  },
  "runtime_clients": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "slug": "text",
      "name": "text",
      "industry": "text",
      "primary_contact_name": "text",
      "primary_contact_email": "text",
      "status": "text",
      "created_by": "text",
      "created_by_label": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "runtime_agency_settings": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "agency_name": "text",
      "primary_color": "text",
      "accent_color": "text",
      "members": "json",
      "updated_by": "text",
      "updated_by_label": "text",
      "updated_at": "text"
    }
  },
  "runtime_event_templates": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "name": "text",
      "description": "text",
      "format": "text",
      "event_type": "text",
      "duration_minutes": "int",
      "sessions": "json",
      "registration_questions": "json",
      "created_by_label": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "runtime_house_defaults": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "from_email": "text",
      "reply_to_email": "text",
      "logo_storage_path": "text",
      "logo_file_name": "text",
      "default_timezone": "text",
      "default_networking_match_minutes": "int",
      "default_attendee_session_days": "int",
      "default_registration_questions": "json",
      "livekit_tier": "text",
      "starter_templates_installed_at": "text",
      "updated_by": "text",
      "updated_by_label": "text",
      "updated_at": "text"
    }
  },
  "request_event_intake": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "name": "text",
      "email": "text",
      "company": "text",
      "event_type": "text",
      "event_date": "text",
      "audience_size": "text",
      "livestream_needs": "text",
      "networking_needs": "text",
      "sponsor_expo_needs": "text",
      "speaker_count": "text",
      "support_level": "text",
      "notes": "text",
      "created_at": "text",
      "budget_range": "text",
      "state": "text",
      "scope_summary": "text",
      "price_amount_cents": "int",
      "price_currency": "text",
      "confirm_token": "text",
      "event_id": "text",
      "approved_at": "text",
      "approved_by": "text",
      "confirmed_at": "text",
      "paid_at": "text",
      "paid_by": "text",
      "settlement_method": "text",
      "settlement_reference": "text",
      "instructions_sent_at": "text",
      "declined_at": "text",
      "decline_reason": "text",
      "updated_at": "text"
    }
  },
  "how_it_works_pages": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "slug"
    ],
    "columns": {
      "slug": "text",
      "title": "text",
      "intro": "text",
      "body": "text",
      "updated_by": "text",
      "updated_by_label": "text",
      "updated_at": "text"
    }
  },
  "event_assets": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "file_name": "text",
      "mime_type": "text",
      "size_bytes": "int",
      "storage_path": "text",
      "external_url": "text",
      "uploaded_by_kind": "text",
      "uploaded_by_label": "text",
      "visibility": "text",
      "status": "text",
      "note": "text",
      "reviewed_by": "text",
      "reviewed_at": "text",
      "archived_at": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "event_backup_rooms": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "event_id",
      "stage_id"
    ],
    "columns": {
      "event_id": "text",
      "stage_id": "text",
      "zoom_meeting_number": "text",
      "zoom_passcode": "text",
      "google_meet_url": "text",
      "updated_by": "text",
      "updated_at": "text"
    }
  },
  "event_code_history": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "field": "text",
      "code": "text",
      "code_key": "text",
      "replaced_at": "text",
      "replaced_by": "text",
      "reason": "text"
    }
  },
  "suppliers": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "kind": "text",
      "name": "text",
      "company": "text",
      "role_or_service": "text",
      "email": "text",
      "phone": "text",
      "rate_kind": "text",
      "rate_amount": "real",
      "notes": "text",
      "status": "text",
      "archived_at": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "supplier_event_links": {
    "file": "migrations-d1/0003_runtime.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "supplier_id": "text",
      "event_id": "text",
      "note": "text",
      "created_at": "text"
    }
  },
  "attendee_profiles": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "event_id",
      "attendee_id"
    ],
    "columns": {
      "attendee_id": "text",
      "event_id": "text",
      "email_hash": "text",
      "name": "text",
      "email_masked": "text",
      "company": "text",
      "title": "text",
      "personal_website": "text",
      "social_links": "json",
      "reason_for_attending": "text",
      "interesting_fact": "text",
      "topics_of_interest": "json",
      "networking_goals": "text",
      "networking_opt_in": "bool",
      "role": "text",
      "status": "text",
      "created_at": "text",
      "updated_at": "text",
      "hidden_from_directory": "bool",
      "email": "text",
      "extra_answers": "json"
    }
  },
  "attendee_sessions": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "event_id",
      "session_id"
    ],
    "columns": {
      "session_id": "text",
      "attendee_id": "text",
      "event_id": "text",
      "role": "text",
      "status": "text",
      "issued_at": "text",
      "expires_at": "text",
      "last_seen_at": "text",
      "client_build_id": "text",
      "client_browser": "text",
      "client_connection_quality": "text",
      "client_subscribed_tracks": "int",
      "client_surface": "text",
      "last_chat_poll_at": "text"
    }
  },
  "attendee_permissions": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "attendee_id": "text",
      "event_id": "text",
      "permission_kind": "text",
      "granted": "bool",
      "granted_by": "text",
      "reason": "text",
      "updated_at": "text"
    }
  },
  "attendee_live_capabilities": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "key"
    ],
    "columns": {
      "key": "text",
      "event_id": "text",
      "room_kind": "text",
      "room_id": "text",
      "attendee_id": "text",
      "capability": "json",
      "updated_at": "text"
    }
  },
  "attendee_live_control_states": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "key"
    ],
    "columns": {
      "key": "text",
      "event_id": "text",
      "room_kind": "text",
      "room_id": "text",
      "state": "json",
      "updated_at": "text"
    }
  },
  "attendee_agenda_intents": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "attendee_id": "text",
      "event_id": "text",
      "planned_session_ids": "json",
      "planned_breakout_ids": "json",
      "planned_sponsor_booth_ids": "json",
      "wants_session_reminders": "bool",
      "updated_at": "text"
    }
  },
  "special_guest_profiles": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "event_id",
      "guest_id"
    ],
    "columns": {
      "guest_id": "text",
      "event_id": "text",
      "role": "text",
      "name": "text",
      "company": "text",
      "title": "text",
      "created_at": "text",
      "updated_at": "text",
      "email": "text"
    }
  },
  "event_guest_states": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "key"
    ],
    "columns": {
      "key": "text",
      "event_id": "text",
      "kind": "text",
      "guest_id": "text",
      "state": "json",
      "updated_at": "text"
    }
  },
  "sponsor_lead_opt_ins": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "attendee_id": "text",
      "event_id": "text",
      "sponsor_booth_id": "text",
      "allowed_fields": "json",
      "created_at": "text"
    }
  },
  "stage_stream_states": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "event_id",
      "stage_id"
    ],
    "columns": {
      "event_id": "text",
      "stage_id": "text",
      "state": "json",
      "updated_at": "text"
    }
  },
  "stage_stream_events": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "stage_id": "text",
      "signal": "text",
      "state_event": "json",
      "created_at": "text"
    }
  },
  "live_chat_messages": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "room_kind": "text",
      "room_id": "text",
      "attendee_id": "text",
      "display_name": "text",
      "company": "text",
      "message": "text",
      "moderation_status": "text",
      "created_at": "text",
      "moderated_by": "text",
      "moderated_at": "text",
      "archived_at": "text",
      "archived_by": "text"
    }
  },
  "live_chat_moderation_states": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "key"
    ],
    "columns": {
      "key": "text",
      "event_id": "text",
      "room_kind": "text",
      "room_id": "text",
      "scope": "text",
      "attendee_id": "text",
      "state": "json",
      "updated_at": "text"
    }
  },
  "live_chat_post_rates": {
    "file": "migrations-d1/0004_attendees_live.sql",
    "primaryKey": [
      "key"
    ],
    "columns": {
      "key": "text",
      "event_id": "text",
      "attendee_id": "text",
      "state": "json",
      "updated_at": "text"
    }
  },
  "networking_queue_entries": {
    "file": "migrations-d1/0005_networking_email.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "attendee_id": "text",
      "display_name": "text",
      "company": "text",
      "title": "text",
      "status": "text",
      "joined_at": "text",
      "matched_at": "text",
      "match_id": "text",
      "matches_completed": "int",
      "updated_at": "text"
    }
  },
  "networking_queue_matches": {
    "file": "migrations-d1/0005_networking_email.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "attendee_a_id": "text",
      "attendee_b_id": "text",
      "normalized_pair_key": "text",
      "room_name": "text",
      "status": "text",
      "starts_at": "text",
      "expires_at": "text",
      "ended_at": "text",
      "ended_reason": "text"
    }
  },
  "runtime_email_sends": {
    "file": "migrations-d1/0005_networking_email.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "agency_id": "text",
      "client_id": "text",
      "workflow_type": "text",
      "recipient_email": "text",
      "recipient_name": "text",
      "subject": "text",
      "provider": "text",
      "provider_message_id": "text",
      "status": "text",
      "action_url": "text",
      "failure_reason": "text",
      "sent_by": "text",
      "queued_at": "text",
      "sent_at": "text",
      "failed_at": "text",
      "group_send_id": "text"
    }
  },
  "runtime_email_group_sends": {
    "file": "migrations-d1/0005_networking_email.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "audience": "text",
      "audience_label": "text",
      "workflow_type": "text",
      "subject": "text",
      "recipient_count": "int",
      "sent_count": "int",
      "failed_count": "int",
      "suppressed_count": "int",
      "sent_by": "text",
      "created_at": "text"
    }
  },
  "runtime_email_unsubscribes": {
    "file": "migrations-d1/0005_networking_email.sql",
    "primaryKey": [
      "email"
    ],
    "columns": {
      "email": "text",
      "email_hash": "text",
      "unsubscribed_at": "text",
      "unsubscribed_source": "text",
      "last_event_id": "text",
      "resubscribed_at": "text",
      "resubscribed_by": "text"
    }
  },
  "v5_access_attempt_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "access_kind": "text",
      "role": "text",
      "status": "text",
      "route": "text",
      "reason": "text",
      "ip_hash": "text",
      "user_agent_hash": "text",
      "created_at": "text"
    }
  },
  "v5_analytics_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "kind": "text",
      "subject_id": "text",
      "metadata": "json",
      "created_at": "text"
    }
  },
  "v5_runtime_fallback_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "room_id": "text",
      "room_type": "text",
      "provider": "text",
      "action": "text",
      "actor_role": "text",
      "reason": "text",
      "created_at": "text"
    }
  },
  "v6_email_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "template_key": "text",
      "recipient_segment": "text",
      "status": "text",
      "provider_message_id": "text",
      "reason": "text",
      "created_at": "text"
    }
  },
  "v6_incident_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "title": "text",
      "severity": "text",
      "status": "text",
      "owner_role": "text",
      "details": "text",
      "created_at": "text"
    }
  },
  "v6_registration_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "attendee_email_hash": "text",
      "status": "text",
      "created_at": "text",
      "display_name": "text",
      "company": "text",
      "title": "text",
      "personal_website": "text",
      "social_links": "json",
      "reason_for_attending": "text",
      "interesting_fact": "text"
    }
  },
  "v6_room_fallback_states": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "event_id",
      "room_type"
    ],
    "columns": {
      "event_id": "text",
      "room_type": "text",
      "state": "json",
      "updated_at": "text"
    }
  },
  "v6_run_of_show_runtime_events": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "segment_id": "text",
      "action": "text",
      "actor_role": "text",
      "created_at": "text"
    }
  },
  "v6_support_requests": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "event_id": "text",
      "attendee_id": "text",
      "subject": "text",
      "status": "text",
      "created_at": "text"
    }
  },
  "auth_users": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "id"
    ],
    "columns": {
      "id": "text",
      "email": "text",
      "full_name": "text",
      "password_hash": "text",
      "password_salt": "text",
      "password_iterations": "int",
      "status": "text",
      "created_at": "text",
      "updated_at": "text"
    }
  },
  "auth_sessions": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "token_hash"
    ],
    "columns": {
      "token_hash": "text",
      "user_id": "text",
      "created_at": "text",
      "expires_at": "text",
      "revoked_at": "text"
    }
  },
  "auth_password_resets": {
    "file": "migrations-d1/0006_events_audit_auth.sql",
    "primaryKey": [
      "token_hash"
    ],
    "columns": {
      "token_hash": "text",
      "user_id": "text",
      "created_at": "text",
      "expires_at": "text",
      "used_at": "text"
    }
  }
};
