import type { TestingConsoleSnapshot } from "@/types/testing";

export const baselineTestingConsoleSnapshot: TestingConsoleSnapshot = {
  eventId: "event-summit",
  overallStatus: "warn",
  goNoGo: "monitor",
  recoveryMode: "producer_intervention",
  whiteLabelBackupProvider: "daily",
  whiteLabelBackupLabel: "West Peek Live! Daily Backup Room",
  whiteLabelBackupUrl: "https://westpeeklive.daily.co/client-safe-room",
  whiteLabelBackupEnabled: true,
  generatedAt: "2026-05-18T16:15:00.000Z",
  fallbackOrder: ["livekit", "cloudflare_stream", "daily", "zoom_sdk", "google_meet"],
  dailyAutomaticFallbackEnabled: true,
  checks: [
    {
      id: "check-browser",
      label: "Browser compatibility",
      description: "Confirms supported browser, secure context, and required media APIs.",
      status: "pass",
      severity: "medium",
      recommendedAction: "No action needed.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
      metadata: { browser: "Chrome", secureContext: true },
    },
    {
      id: "check-camera-permission",
      label: "Camera permission",
      description: "Confirms the browser has camera permission before joining stage or backstage.",
      status: "pass",
      severity: "high",
      recommendedAction: "No action needed.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
    },
    {
      id: "check-microphone-permission",
      label: "Microphone permission",
      description: "Confirms microphone access and detects input signal.",
      status: "warn",
      severity: "critical",
      recommendedAction: "Ask speaker to select the correct microphone and repeat the audio test.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
      metadata: { inputLevel: 12, expectedMinimum: 25 },
    },
    {
      id: "check-speaker-output",
      label: "Speaker output",
      description: "Confirms user can hear a test tone or stage audio sample.",
      status: "pending",
      severity: "high",
      recommendedAction: "Run manual speaker output test before rehearsal.",
    },
    {
      id: "check-network",
      label: "Network quality",
      description: "Tracks latency, packet loss, and connection stability.",
      status: "warn",
      severity: "critical",
      recommendedAction: "Move speaker to wired internet or open the white-label backup room only if in-platform recovery fails.",
      lastRunAt: "2026-05-18T16:14:00.000Z",
      metadata: { latencyMs: 142, packetLossPercent: 2.7 },
    },
    {
      id: "check-recording",
      label: "Recording readiness",
      description: "Confirms recording hook/status for rooms that require replay.",
      status: "skipped",
      severity: "medium",
      recommendedAction: "Recording requires LiveKit egress activation before production use.",
    },
  ],
  devices: [
    {
      id: "device-camera",
      kind: "camera",
      label: "Camera preview",
      status: "pass",
      details: "Camera permission granted. Browser preview stream is available.",
      recommendedAction: "Confirm framing and lighting with speaker.",
    },
    {
      id: "device-microphone",
      kind: "microphone",
      label: "Microphone input",
      status: "warn",
      details: "Input is detected but below target level.",
      recommendedAction: "Switch microphone, raise input gain, or move closer.",
    },
    {
      id: "device-speaker",
      kind: "speaker",
      label: "Speaker output",
      status: "pending",
      details: "Manual confirmation required.",
      recommendedAction: "Play test tone and ask operator to confirm.",
    },
    {
      id: "device-network",
      kind: "network",
      label: "Network quality",
      status: "warn",
      details: "Latency and packet loss are above ideal show conditions.",
      recommendedAction: "Use wired internet or prepare fallback room.",
    },
  ],
  rooms: [
    {
      id: "room-main-stage",
      eventId: "event-summit",
      roomName: "Main Stage",
      roomType: "main_stage",
      provider: "livekit",
      status: "warn",
      joinTestStatus: "pass",
      audioStatus: "warn",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 142,
      packetLossPercent: 2.7,
      recommendedAction: "Run speaker audio test again and open the white-label backup room only if in-platform recovery fails link.",
    },
    {
      id: "room-daily-automatic-fallback",
      eventId: "event-summit",
      roomName: "Daily Automatic Backup",
      roomType: "rehearsal_room",
      provider: "daily",
      status: "pass",
      joinTestStatus: "pass",
      audioStatus: "pass",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 94,
      packetLossPercent: 0.2,
      recommendedAction: "Daily is staged as the automatic in-platform backup before Zoom or Google Meet escalation.",
    },
    {
      id: "room-backstage",
      eventId: "event-summit",
      roomName: "Backstage",
      roomType: "backstage",
      provider: "livekit",
      status: "pass",
      joinTestStatus: "pass",
      audioStatus: "pass",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 88,
      packetLossPercent: 0.4,
      recommendedAction: "No action needed.",
    },
    {
      id: "room-breakout-a",
      eventId: "event-summit",
      roomName: "Breakout A",
      roomType: "breakout_session",
      provider: "livekit",
      status: "pending",
      joinTestStatus: "pending",
      audioStatus: "pending",
      videoStatus: "pending",
      recordingStatus: "skipped",
      recommendedAction: "Run preflight before opening room.",
    },
    {
      id: "room-speed-networking",
      eventId: "event-summit",
      roomName: "Speed Networking Matchmaking",
      roomType: "networking_match",
      provider: "livekit",
      status: "warn",
      joinTestStatus: "pass",
      audioStatus: "pending",
      videoStatus: "pending",
      recordingStatus: "skipped",
      latencyMs: 96,
      packetLossPercent: 0.8,
      recommendedAction: "Run matchmaking queue, no-repeat pair, timer, skip, and report-issue checks before opening networking to attendees.",
    },
    {
      id: "room-clarity-booth",
      eventId: "event-summit",
      roomName: "Clarity Booth",
      roomType: "sponsor_booth",
      provider: "livekit",
      status: "pass",
      joinTestStatus: "pass",
      audioStatus: "pass",
      videoStatus: "pass",
      recordingStatus: "skipped",
      latencyMs: 72,
      packetLossPercent: 0.1,
      recommendedAction: "No action needed.",
    },
  ],
  smokeChecks: [
    {
      id: "smoke-domain",
      label: "Production domain route smoke",
      description: "Confirms westpeek.live priority routes return 200 and render visible West Peek Live content.",
      status: "pass",
      severity: "critical",
      recommendedAction: "Run after each deploy and before event rehearsal.",
      metadata: { domain: "westpeek.live" },
    },
    {
      id: "smoke-livekit",
      label: "LiveKit token smoke",
      description: "Confirms primary LiveKit token generation returns a server-issued token and LiveKit URL.",
      status: "pass",
      severity: "critical",
      recommendedAction: "Keep LiveKit as primary provider unless this check fails.",
    },
    {
      id: "smoke-daily",
      label: "Daily automatic fallback smoke",
      description: "Confirms Daily API key, domain, room creation, and meeting token readiness for automatic fallback.",
      status: "pass",
      severity: "critical",
      recommendedAction: "Daily is automatic when DAILY_FALLBACK_ENABLED=true; no producer approval required.",
      metadata: { dailyFallbackEnabled: true },
    },
    {
      id: "smoke-zoom",
      label: "Zoom embedded signature smoke",
      description: "Confirms Zoom Meeting SDK signature generation is available after Daily fallback.",
      status: "pass",
      severity: "high",
      recommendedAction: "Use only after LiveKit and Daily are unavailable or unsuitable.",
    },
    {
      id: "smoke-google-meet",
      label: "Google Meet managed fallback config",
      description: "Confirms the final managed fallback URL can be configured for emergency use.",
      status: "pending",
      severity: "medium",
      recommendedAction: "Populate GOOGLE_MEET_MANAGED_FALLBACK_URL before client-facing disaster recovery drills.",
    },
    {
      id: "smoke-resend",
      label: "Resend production email smoke",
      description: "Confirms notifications send from notifications@events.westpeek.live.",
      status: "pass",
      severity: "critical",
      recommendedAction: "Run after sender-domain or secret changes.",
    },
    {
      id: "smoke-d1",
      label: "D1 write/read smoke",
      description: "Confirms a write and read against the production D1 database succeed.",
      status: "pass",
      severity: "critical",
      recommendedAction: "Run after schema, RLS, or secret changes.",
    },
    {
      id: "smoke-browser-console",
      label: "Browser console scan",
      description: "Confirms priority pages have zero console/page errors in Chromium.",
      status: "pass",
      severity: "high",
      recommendedAction: "Run after UI, routing, or deployment adapter changes.",
    },
  ],
  incidents: [
    {
      id: "incident-audio-low",
      eventId: "event-summit",
      title: "Main stage speaker audio low",
      severity: "high",
      status: "monitoring",
      summary: "Audio input detected but level is below recommended threshold.",
      platformRecoveryRequired: false,
      createdAt: "2026-05-18T16:12:00.000Z",
    },
    {
      id: "incident-network",
      eventId: "event-summit",
      title: "Speaker network instability",
      severity: "critical",
      status: "open",
      summary: "Packet loss above safe show threshold for main stage guest.",
      platformRecoveryRequired: true,
      createdAt: "2026-05-18T16:13:00.000Z",
    },
  ],
};
