-- 0002_approvals_inbox: D1 (SQLite) schema. Flattened from the Postgres migrations db/migrations/0001-0046
-- (last held at commit 984ea43); generated from their introspected shape, then reviewed.
-- Types: uuid/timestamptz -> TEXT (ISO-8601 UTC), jsonb/text[] -> TEXT CHECK(json_valid),
-- boolean -> INTEGER 0/1. Ids are minted in Worker code (crypto.randomUUID()).

CREATE TABLE IF NOT EXISTS approval_requests (
  id TEXT NOT NULL,
  agency_id TEXT NOT NULL,
  client_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  approval_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  requested_by_user_id TEXT,
  assigned_to_user_id TEXT,
  assigned_role TEXT,
  due_at TEXT,
  client_visible INTEGER NOT NULL DEFAULT 1 CHECK (client_visible IN (0, 1)),
  locked INTEGER NOT NULL DEFAULT 0 CHECK (locked IN (0, 1)),
  approved_at TEXT,
  approved_by_user_id TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  deleted_at TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  FOREIGN KEY (approved_by_user_id) REFERENCES profiles(id),
  FOREIGN KEY (assigned_to_user_id) REFERENCES profiles(id),
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (requested_by_user_id) REFERENCES profiles(id)
);
CREATE INDEX IF NOT EXISTS idx_approvals_event_status ON approval_requests (event_id, status);

CREATE TABLE IF NOT EXISTS approval_comments (
  id TEXT NOT NULL,
  agency_id TEXT NOT NULL,
  client_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  approval_request_id TEXT NOT NULL,
  author_user_id TEXT,
  body TEXT NOT NULL,
  visibility TEXT NOT NULL DEFAULT 'client_facing',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  deleted_at TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  FOREIGN KEY (approval_request_id) REFERENCES approval_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (author_user_id) REFERENCES profiles(id),
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS production_inbox_items (
  id TEXT NOT NULL,
  agency_id TEXT NOT NULL,
  client_id TEXT,
  event_id TEXT,
  event_code TEXT NOT NULL,
  source_channel TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new',
  sender_name TEXT NOT NULL,
  sender_email TEXT NOT NULL,
  subject TEXT NOT NULL,
  summary TEXT,
  possible_match_type TEXT,
  possible_match_id TEXT,
  linked_resource_type TEXT,
  linked_resource_id TEXT,
  next_action TEXT,
  received_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  converted_at TEXT,
  archived_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (id),
  FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_production_inbox_event_status ON production_inbox_items (event_id, status, received_at);

CREATE TABLE IF NOT EXISTS last_minute_change_requests (
  id TEXT NOT NULL,
  agency_id TEXT NOT NULL,
  client_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  speaker_id TEXT,
  sponsor_id TEXT,
  run_of_show_segment_id TEXT,
  change_type TEXT NOT NULL,
  urgency TEXT NOT NULL DEFAULT 'normal',
  risk TEXT NOT NULL DEFAULT 'low',
  status TEXT NOT NULL DEFAULT 'submitted',
  title TEXT NOT NULL,
  old_version_label TEXT,
  new_version_label TEXT,
  diff_summary TEXT,
  affects_timing INTEGER NOT NULL DEFAULT 0 CHECK (affects_timing IN (0, 1)),
  affects_sponsor_mention INTEGER NOT NULL DEFAULT 0 CHECK (affects_sponsor_mention IN (0, 1)),
  affects_client_approved_copy INTEGER NOT NULL DEFAULT 0 CHECK (affects_client_approved_copy IN (0, 1)),
  minutes_until_segment INTEGER NOT NULL DEFAULT 0,
  recommended_action TEXT,
  submitted_by_user_id TEXT,
  decided_by_user_id TEXT,
  submitted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  decided_at TEXT,
  pushed_to_live_at TEXT,
  rolled_back_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (id),
  FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  FOREIGN KEY (decided_by_user_id) REFERENCES profiles(id),
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (submitted_by_user_id) REFERENCES profiles(id)
);
CREATE INDEX IF NOT EXISTS idx_last_minute_changes_event_status ON last_minute_change_requests (event_id, status, urgency);
CREATE INDEX IF NOT EXISTS idx_last_minute_changes_risk ON last_minute_change_requests (event_id, risk);
