const fs = require("fs");
const path = require("path");
/**
 * The manual is one source of truth in docs/, and the app renders it. A Worker cannot read the
 * repo at runtime, so this copies the markdown into a generated module and the screenshots into
 * public/, rewriting the image paths as it goes. Run by the build and checked by a validator, so
 * the in-app manual can never drift from the file.
 */
const SOURCE = "docs/WEST_PEEK_LIVE_OPERATOR_MANUAL_V3.md";
const IMAGE_DIR = "docs/images/manual";
const PUBLIC_IMAGE_DIR = path.join("public", "manual", "images");
const GENERATED = path.join("lib", "manual", "manualSource.generated.ts");

function build() {
  const markdown = fs.readFileSync(SOURCE, "utf8").replace(/\]\((?:\.\/)?(?:docs\/)?images\/manual\//g, "](/manual/images/");
  fs.mkdirSync(PUBLIC_IMAGE_DIR, { recursive: true });
  const copied = [];
  if (fs.existsSync(IMAGE_DIR)) {
    for (const file of fs.readdirSync(IMAGE_DIR)) {
      fs.copyFileSync(path.join(IMAGE_DIR, file), path.join(PUBLIC_IMAGE_DIR, file));
      copied.push(file);
    }
  }
  fs.mkdirSync(path.dirname(GENERATED), { recursive: true });
  const body = `/* GENERATED by scripts/build_manual_assets.js from ${SOURCE}. Do not edit: edit the manual. */\nexport const MANUAL_SOURCE = ${JSON.stringify(markdown)};\nexport const MANUAL_IMAGES = ${JSON.stringify(copied.sort())};\n`;
  const current = fs.existsSync(GENERATED) ? fs.readFileSync(GENERATED, "utf8") : "";
  if (current !== body) fs.writeFileSync(GENERATED, body);
  return { markdown, copied, changed: current !== body };
}

if (require.main === module) {
  const result = build();
  console.log(`build_manual_assets: ${result.changed ? "updated" : "already current"} — ${result.markdown.length} characters, ${result.copied.length} screenshots.`);
}

module.exports = { build, SOURCE, GENERATED, PUBLIC_IMAGE_DIR };
