#!/usr/bin/env node
/**
 * migrations-d1/*.sql is the ONE definition of the database. This reads it and writes
 * lib/d1/schema.generated.ts: every table, every column and its storage kind (text, int, real,
 * bool, json), the primary key, and the migration file that creates it. The D1 query layer encodes
 * and decodes JSON and boolean columns from this, and the health probe checks every table and
 * column in it against the live database, so neither keeps a list of its own.
 *
 *   node scripts/generate_d1_schema_manifest.mjs           write the manifest
 *   node scripts/generate_d1_schema_manifest.mjs --check   fail if the committed manifest is stale
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const dir = path.join(root, "migrations-d1");
const out = path.join(root, "lib/d1/schema.generated.ts");

export function parseD1Migrations(migrationsDir = dir) {
  const files = fs.readdirSync(migrationsDir).filter((f) => /^\d{4}_[a-z0-9_]+\.sql$/.test(f)).sort();
  const tables = {};
  for (const file of files) {
    const sql = fs.readFileSync(path.join(migrationsDir, file), "utf8");
    const re = /CREATE TABLE IF NOT EXISTS (\w+) \(\n([\s\S]*?)\n\);/g;
    let m;
    while ((m = re.exec(sql))) {
      const [, table, body] = m;
      const columns = {};
      let primaryKey = [];
      for (const raw of body.split("\n")) {
        const line = raw.trim().replace(/,$/, "");
        const pk = /^PRIMARY KEY \(([^)]*)\)/.exec(line);
        if (pk) { primaryKey = pk[1].split(",").map((s) => s.trim()); continue; }
        const col = /^([a-z_][a-z0-9_]*) (TEXT|INTEGER|REAL)\b(.*)$/.exec(line);
        if (!col) continue;
        const [, name, type, rest] = col;
        let kind = type === "TEXT" ? "text" : type === "INTEGER" ? "int" : "real";
        if (new RegExp(`CHECK \\(json_valid\\(${name}\\)\\)`).test(rest)) kind = "json";
        else if (new RegExp(`CHECK \\(${name} IN \\(0, 1\\)\\)`).test(rest)) kind = "bool";
        if (/\bPRIMARY KEY\b/.test(rest)) primaryKey = [name];
        columns[name] = kind;
      }
      if (tables[table]) throw new Error(`${table} is created twice (${tables[table].file} and migrations-d1/${file})`);
      tables[table] = { file: `migrations-d1/${file}`, primaryKey, columns };
    }
  }
  return { files, tables };
}

function render({ tables }) {
  return `// GENERATED by scripts/generate_d1_schema_manifest.mjs from migrations-d1/*.sql. Do not edit.
// Regenerate with: node scripts/generate_d1_schema_manifest.mjs
export type D1ColumnKind = "text" | "int" | "real" | "bool" | "json";
export interface D1TableSchema { file: string; primaryKey: string[]; columns: Record<string, D1ColumnKind> }
export const D1_SCHEMA: Record<string, D1TableSchema> = ${JSON.stringify(tables, null, 2)};
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)) {
  const parsed = parseD1Migrations();
  const count = Object.keys(parsed.tables).length;
  if (!count) { console.error("generate_d1_schema_manifest: zero tables parsed from migrations-d1 — refusing to write an empty manifest"); process.exit(1); }
  const text = render(parsed);
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
    if (current !== text) { console.error("lib/d1/schema.generated.ts is stale: run node scripts/generate_d1_schema_manifest.mjs"); process.exit(1); }
    console.log(`d1 schema manifest current: ${count} tables`);
  } else {
    fs.writeFileSync(out, text);
    console.log(`wrote lib/d1/schema.generated.ts: ${count} tables`);
  }
}
