const fs = require("fs");
const path = require("path");

function fail(message) {
  console.error("sync_required_secrets_manifest: FAIL — " + message);
  process.exit(1);
}
function readJson(file) {
  if (!fs.existsSync(file)) fail("missing " + file);
  return JSON.parse(fs.readFileSync(file, "utf8"));
}
function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + "\n");
}
function accessKeys() {
  const access = readJson("data/access/event-access-config.json");
  const keys = new Set();
  for (const eventConfig of Object.values(access.events || {})) {
    if (eventConfig.crewPasswordEnvKey) keys.add(eventConfig.crewPasswordEnvKey);
    for (const item of eventConfig.specialGuestCodes || []) {
      if (item.envKey) keys.add(item.envKey);
    }
  }
  return Array.from(keys).sort();
}

const registryPath = "deployment/env-var-registry.json";
const registry = readJson(registryPath);
const derivedRequired = new Set([...(registry.requiredProductionEnv || []), ...accessKeys()]);
const derivedCloudflare = new Set([...(registry.cloudflareSecretKeys || []), ...accessKeys()]);

registry.requiredProductionEnv = Array.from(derivedRequired).sort();
registry.cloudflareSecretKeys = Array.from(derivedCloudflare).sort();
writeJson(registryPath, registry);

const manifestPath = "deployment/cloudflare-required-secrets.json";
const manifest = fs.existsSync(manifestPath) ? readJson(manifestPath) : {};
manifest.workerName = registry.workerName || "west-peek-live";
manifest.liveSmokeBaseUrl = registry.liveSmokeBaseUrl || "https://west-peek-live.seq-taylor.workers.dev";
manifest.requiredSecrets = registry.cloudflareSecretKeys;
const registryDemoDefaults = registry.demoDefaults || {};
manifest.demoDefaults = {
  ...(manifest.demoDefaults || {}),
  ...registryDemoDefaults,
  AGENCY_EVENT_OS_RUNTIME_STORE: registryDemoDefaults.AGENCY_EVENT_OS_RUNTIME_STORE || "file",
  ALLOW_FILE_RUNTIME_STORE_IN_PRODUCTION: registryDemoDefaults.ALLOW_FILE_RUNTIME_STORE_IN_PRODUCTION || "true",
  VIDEO_PROVIDER: registryDemoDefaults.VIDEO_PROVIDER || "livekit",
  DAILY_FALLBACK_ENABLED: registryDemoDefaults.DAILY_FALLBACK_ENABLED || "true",
  LIVEKIT_INGRESS_RTMP_BASE_URL: registryDemoDefaults.LIVEKIT_INGRESS_RTMP_BASE_URL || "rtmp://livekit-ingress.example.com",
  LIVEKIT_WEBHOOK_SECRET: registryDemoDefaults.LIVEKIT_WEBHOOK_SECRET || "change-me-livekit-webhook-secret",
  STREAMYARD_PRIMARY_ENABLED: registryDemoDefaults.STREAMYARD_PRIMARY_ENABLED || "true",
  STAGE_STREAM_DEFAULT_SOURCE: registryDemoDefaults.STAGE_STREAM_DEFAULT_SOURCE || "LIVEKIT_INGRESS",
  DAILY_STAGE_FALLBACK_REQUIRES_TOKEN: registryDemoDefaults.DAILY_STAGE_FALLBACK_REQUIRES_TOKEN || "true",
  DAILY_API_BASE_URL: registryDemoDefaults.DAILY_API_BASE_URL || "https://api.daily.co/v1"
};
writeJson(manifestPath, manifest);

const envExampleValues = {
  NEXT_PUBLIC_APP_URL: "https://westpeek.live",
  AUTH_SESSION_COOKIE_NAME: "agency_event_os_session",
  V5_CREW_COOKIE_NAME: "wpl_crew_access",
  V5_SPECIAL_GUEST_COOKIE_NAME: "wpl_guest_access",
  V5_OPERATOR_COOKIE_NAME: "wpl_operator_access",
  // These must stay on the verified sending domain and match lib/brand.ts. They used to read
  // "West Peek Live <hello@westpeek.live>" and "support@westpeek.live", both on the apex, which
  // carries no Resend DKIM key — anyone who copied this example into EMAIL_FROM would have had
  // every send rejected. validate_email_sender_identity.js fails if these drift again.
  EMAIL_FROM: "West Peek Live <notifications@events.westpeek.live>",
  EMAIL_REPLY_TO: "hello@westpeek.live",
  VIDEO_PROVIDER: "livekit",
  DAILY_API_BASE_URL: "https://api.daily.co/v1",
  DAILY_FALLBACK_ENABLED: "true",
  LIVEKIT_INGRESS_RTMP_BASE_URL: "rtmp://livekit-ingress.example.com",
  LIVEKIT_WEBHOOK_SECRET: "change-me-livekit-webhook-secret",
  STREAMYARD_PRIMARY_ENABLED: "true",
  STAGE_STREAM_DEFAULT_SOURCE: "LIVEKIT_INGRESS",
  DAILY_STAGE_FALLBACK_REQUIRES_TOKEN: "true",
  AGENCY_EVENT_OS_RUNTIME_STORE: "supabase",
  ALLOW_FILE_RUNTIME_STORE_IN_PRODUCTION: "false",
  NEXT_PUBLIC_SELF_SERVE_ENABLED: "false",
  SELF_SERVE_EVENT_CREATION_ENABLED: "false",
  BILLING_REQUIRED_FOR_SELF_SERVE: "true"
};
const lines = [
  "# West Peek Live environment registry example.",
  "# Never commit real secrets. Production values must be set in Cloudflare Worker secrets/vars.",
  "# Generated by scripts/sync_required_secrets_manifest.js.",
  ""
];
for (const key of registry.requiredProductionEnv) {
  lines.push(`${key}=${envExampleValues[key] || ""}`);
}
lines.push("", "# Optional/dev-only values. These are not production-complete signals.");
for (const key of registry.optionalDevEnv || []) lines.push(`${key}=`);
fs.writeFileSync(".env.example", lines.join("\n") + "\n");

console.log("sync_required_secrets_manifest: PASS");
console.log("Required production env keys: " + registry.requiredProductionEnv.length);
console.log("Cloudflare required secret names: " + registry.cloudflareSecretKeys.length);
